// <auto-generated />
using System;
using Crumbs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Crumbs.Data.Migrations
{
    [DbContext(typeof(CrumbsDbContext))]
    [Migration("20210714173547_AddCrumbsUuid")]
    partial class AddCrumbsUuid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Crumbs.Data.Models.Crumb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("BroadcasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BroadcasterId");

                    b.ToTable("Crumbs");
                });

            modelBuilder.Entity("Crumbs.Data.Models.Crumb", b =>
                {
                    b.HasOne("Crumbs.Data.Models.Crumb", "Broadcaster")
                        .WithMany("Observers")
                        .HasForeignKey("BroadcasterId");

                    b.Navigation("Broadcaster");
                });

            modelBuilder.Entity("Crumbs.Data.Models.Crumb", b =>
                {
                    b.Navigation("Observers");
                });
#pragma warning restore 612, 618
        }
    }
}
