// <auto-generated />
using System;
using Crumbs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Crumbs.Data.Migrations
{
    [DbContext(typeof(CrumbsDbContext))]
    [Migration("20210725161752_AddUserTableWithRelationToCrumbs")]
    partial class AddUserTableWithRelationToCrumbs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Crumbs.Data.Models.Crumb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("BroadcasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("UserId");

                    b.ToTable("Crumbs");
                });

            modelBuilder.Entity("Crumbs.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Crumbs.Data.Models.Crumb", b =>
                {
                    b.HasOne("Crumbs.Data.Models.Crumb", "Broadcaster")
                        .WithMany("Observers")
                        .HasForeignKey("BroadcasterId");

                    b.HasOne("Crumbs.Data.Models.User", "User")
                        .WithMany("Crumbs")
                        .HasForeignKey("UserId");

                    b.Navigation("Broadcaster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Crumbs.Data.Models.Crumb", b =>
                {
                    b.Navigation("Observers");
                });

            modelBuilder.Entity("Crumbs.Data.Models.User", b =>
                {
                    b.Navigation("Crumbs");
                });
#pragma warning restore 612, 618
        }
    }
}
