version: "3"
services:
  postgres:
    image: clkao/postgres-plv8
    container_name: postgres_crumbs
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: PostgresPassword14$$
    ports:
      - "15432:5432"
    networks:
      - es_network
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_crumbs
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - es_network
      
networks:
  es_network:
    driver: bridge
