# curl --header "Content-Type: application/json" --request POST --data '{"username":"xyz","password":"xyz"}' http://localhost:3000/api/login
POST {{host}}/crumb/add
Content-Type: application/json

{
  "Uuid":"",
  "Name":"crumb sample name",
  "Description":"sample description",
  "Type":0,
  "BroadcasterId":null
}

###

### Get all crumbs
GET {{host}}/crumb HTTP/1.1

